id: 88765d3021824619b5d53a523acff0b0
initial_creation_type: ocr
source_metadata:
  volumes:
    5b2078dea22447b18aa1c7002244a251:
      base_file: v022.txt
      image_group_id: I1PD95867
      title: ''
      total_pages: 1409
      volume_number: 22
